const distractors = [
  'invoice',
  'agenda',
  'budget',
  'vendor',
  'policy',
  'shipment',
  'deadline',
  'contract',
  'platform',
  'outage',
  'refund',
  'proposal',
]

const rawWords = [
  ['implement', 'v.', '实施，执行', 'TOEIC', '核心', ['项目', '管理'], 'implement a policy', 'The team will implement the new security policy next Monday.', '团队将在下周一实施新的安全政策。'],
  ['allocate', 'v.', '分配，拨出', 'TOEIC', '高频', ['预算', '资源'], 'allocate resources', 'The manager will allocate more resources to the urgent project.', '经理会给紧急项目分配更多资源。'],
  ['estimate', 'n./v.', '估算，预估', 'TOEIC', '核心', ['报价', '计划'], 'provide an estimate', 'Could you provide an estimate before we approve the budget?', '在我们批准预算前，你能提供一份估算吗？'],
  ['invoice', 'n.', '发票，账单', 'TOEIC', '核心', ['财务', '采购'], 'issue an invoice', 'The vendor will issue an invoice after the equipment is delivered.', '供应商会在设备交付后开具发票。'],
  ['vendor', 'n.', '供应商，卖方', 'TOEIC', '核心', ['采购', '合作'], 'select a vendor', 'We need to select a vendor before the end of this month.', '我们需要在本月底前选定供应商。'],
  ['agenda', 'n.', '议程', 'TOEIC', '核心', ['会议', '沟通'], 'meeting agenda', 'Please review the agenda before tomorrow morning meeting.', '请在明早会议前查看议程。'],
  ['proposal', 'n.', '提案，建议书', 'TOEIC', '核心', ['销售', '项目'], 'submit a proposal', 'The sales team submitted a proposal for the new client.', '销售团队为新客户提交了一份提案。'],
  ['contract', 'n.', '合同', 'TOEIC', '核心', ['法务', '采购'], 'sign a contract', 'Both companies agreed to sign a contract next week.', '两家公司同意下周签署合同。'],
  ['deadline', 'n.', '截止日期', 'TOEIC', '核心', ['任务', '项目'], 'meet a deadline', 'The report must be finished before the deadline.', '报告必须在截止日期前完成。'],
  ['revenue', 'n.', '收入，营收', 'TOEIC', '高频', ['财务', '销售'], 'increase revenue', 'Online sales helped the company increase revenue this quarter.', '线上销售帮助公司本季度提高了营收。'],
  ['expense', 'n.', '费用，开支', 'TOEIC', '高频', ['财务', '报销'], 'travel expense', 'Employees should submit each travel expense within five business days.', '员工应在五个工作日内提交每笔差旅费用。'],
  ['inventory', 'n.', '库存', 'TOEIC', '高频', ['仓储', '运营'], 'check inventory', 'The warehouse team checks inventory every Friday afternoon.', '仓库团队每周五下午检查库存。'],
  ['shipment', 'n.', '货运，发货', 'TOEIC', '高频', ['物流', '采购'], 'track a shipment', 'The customer wants to track the shipment in real time.', '客户想实时跟踪货运。'],
  ['refund', 'n./v.', '退款', 'TOEIC', '高频', ['客服', '财务'], 'process a refund', 'The support agent processed a refund after confirming the issue.', '客服确认问题后处理了退款。'],
  ['warranty', 'n.', '保修，质保', 'TOEIC', '高频', ['售后', '产品'], 'under warranty', 'The printer is still under warranty, so the repair is free.', '打印机仍在保修期内，所以维修免费。'],
  ['branch', 'n.', '分店，分支机构', 'TOEIC', '核心', ['组织', '门店'], 'open a branch', 'The company will open a branch in Shenzhen next year.', '公司明年将在深圳开设分支机构。'],
  ['candidate', 'n.', '候选人', '工作', '核心', ['HR', '招聘'], 'interview a candidate', 'The HR manager will interview a candidate this afternoon.', '人事经理今天下午会面试一位候选人。'],
  ['resume', 'n.', '简历', '工作', '核心', ['HR', '招聘'], 'review a resume', 'Please review the resume before you schedule the interview.', '安排面试前请先查看简历。'],
  ['onboarding', 'n.', '入职培训，导入流程', '工作', '高频', ['HR', '流程'], 'employee onboarding', 'The onboarding process helps new employees understand internal tools.', '入职流程帮助新员工了解内部工具。'],
  ['benefit', 'n.', '福利，好处', '工作', '核心', ['HR', '制度'], 'employee benefit', 'The company offers a health benefit to full-time employees.', '公司为全职员工提供健康福利。'],
  ['promotion', 'n.', '晋升，促销', '工作', '高频', ['HR', '销售'], 'receive a promotion', 'She received a promotion after leading two successful projects.', '她带领两个项目成功后获得了晋升。'],
  ['performance', 'n.', '绩效，表现', '工作', '核心', ['HR', '管理'], 'performance review', 'The performance review will focus on goals and results.', '绩效评估将关注目标和结果。'],
  ['attendance', 'n.', '出勤，参加人数', '工作', '高频', ['HR', '会议'], 'track attendance', 'The system can track attendance for every training session.', '系统可以跟踪每次培训的出勤情况。'],
  ['policy', 'n.', '政策，制度', '工作', '核心', ['制度', '合规'], 'company policy', 'All employees must follow the company policy on data security.', '所有员工都必须遵守公司的数据安全制度。'],
  ['procedure', 'n.', '流程，程序', '工作', '核心', ['流程', '运营'], 'standard procedure', 'This document explains the standard procedure for returns.', '这份文件说明了退货的标准流程。'],
  ['compliance', 'n.', '合规，遵守', '工作', '核心', ['制度', '审计'], 'ensure compliance', 'The audit team checks compliance with internal rules.', '审计团队检查内部规则的合规情况。'],
  ['audit', 'n./v.', '审计，审核', '工作', '高频', ['财务', '合规'], 'conduct an audit', 'The finance department will conduct an audit next month.', '财务部门下个月会进行审计。'],
  ['negotiate', 'v.', '谈判，协商', '工作', '核心', ['销售', '采购'], 'negotiate a contract', 'We need to negotiate the contract terms with the supplier.', '我们需要和供应商协商合同条款。'],
  ['coordinate', 'v.', '协调', '工作', '核心', ['项目', '沟通'], 'coordinate schedules', 'The assistant will coordinate schedules for the visiting team.', '助理会协调来访团队的日程。'],
  ['prioritize', 'v.', '优先处理', '工作', '核心', ['任务', '沟通'], 'prioritize requests', 'Please prioritize customer requests that affect payment processing.', '请优先处理影响付款流程的客户请求。'],
  ['collaborate', 'v.', '协作', '工作', '高频', ['团队', '项目'], 'collaborate with a team', 'Designers and engineers collaborate on the product launch.', '设计师和工程师协作完成产品发布。'],
  ['delegate', 'v.', '委派，授权', '工作', '进阶', ['管理', '团队'], 'delegate tasks', 'A good manager knows when to delegate tasks to the team.', '优秀经理知道何时把任务委派给团队。'],
  ['briefing', 'n.', '简报，情况说明会', '工作', '进阶', ['会议', '汇报'], 'daily briefing', 'The daily briefing starts at nine in the conference room.', '每日简报会九点在会议室开始。'],
  ['stakeholder', 'n.', '利益相关者', '工作', '进阶', ['项目', '管理'], 'key stakeholder', 'The project manager updated each stakeholder on the delay.', '项目经理向每位利益相关者通报了延期情况。'],
  ['milestone', 'n.', '里程碑，阶段目标', '工作', '进阶', ['项目', '计划'], 'project milestone', 'The first project milestone is the prototype review.', '第一个项目里程碑是原型评审。'],
  ['deliverable', 'n.', '交付物', '工作', '进阶', ['项目', '交付'], 'final deliverable', 'The final deliverable must include a user guide.', '最终交付物必须包含用户指南。'],
  ['feedback', 'n.', '反馈', '工作', '核心', ['沟通', '产品'], 'collect feedback', 'We collect feedback from users after every release.', '每次发布后我们都会收集用户反馈。'],
  ['approval', 'n.', '批准，许可', '工作', '核心', ['流程', '管理'], 'get approval', 'The design needs approval before development begins.', '设计需要获得批准后才能开始开发。'],
  ['authorize', 'v.', '授权，批准', '工作', '进阶', ['流程', '财务'], 'authorize payment', 'Only the finance director can authorize this payment.', '只有财务总监能批准这笔付款。'],
  ['reimburse', 'v.', '报销，偿还', 'TOEIC', '高频', ['财务', 'HR'], 'reimburse expenses', 'The company will reimburse approved travel expenses.', '公司会报销已批准的差旅费用。'],
  ['commute', 'v./n.', '通勤', 'TOEIC', '核心', ['日常', '交通'], 'daily commute', 'The new office reduces my daily commute by twenty minutes.', '新办公室让我的日常通勤减少了二十分钟。'],
  ['relocate', 'v.', '搬迁，调动', 'TOEIC', '高频', ['办公', 'HR'], 'relocate an office', 'The company plans to relocate its office downtown.', '公司计划把办公室搬到市中心。'],
  ['renovate', 'v.', '翻新，整修', 'TOEIC', '高频', ['办公', '设施'], 'renovate a lobby', 'The hotel will renovate the lobby during the winter.', '酒店会在冬季翻新大堂。'],
  ['facility', 'n.', '设施，场所', 'TOEIC', '核心', ['办公', '运营'], 'training facility', 'The training facility can hold sixty employees.', '培训设施可容纳六十名员工。'],
  ['equipment', 'n.', '设备', 'TOEIC', '核心', ['采购', '办公'], 'office equipment', 'New office equipment will arrive on Wednesday.', '新的办公设备将在周三到达。'],
  ['maintenance', 'n.', '维护，保养', 'TOEIC', '高频', ['设施', '运维'], 'regular maintenance', 'The elevator is closed for regular maintenance.', '电梯因定期维护而关闭。'],
  ['subscription', 'n.', '订阅', '科技', '高频', ['SaaS', '销售'], 'monthly subscription', 'The monthly subscription includes cloud storage.', '月度订阅包含云存储。'],
  ['dashboard', 'n.', '仪表盘，数据面板', '科技', '核心', ['数据', '产品'], 'analytics dashboard', 'The dashboard shows revenue, traffic, and conversion rate.', '数据面板显示营收、流量和转化率。'],
  ['deploy', 'v.', '部署，发布', '科技', '高频', ['软件', '运维'], 'deploy an update', 'The engineer will deploy the update after final testing.', '工程师会在最终测试后部署更新。'],
  ['scalable', 'adj.', '可扩展的', '科技', '进阶', ['产品', '架构'], 'scalable platform', 'A scalable platform can support more users without redesign.', '可扩展平台无需重做也能支持更多用户。'],
  ['outage', 'n.', '中断，停机', '科技', '进阶', ['运维', '服务'], 'service outage', 'The service outage lasted twenty minutes and affected orders.', '服务中断持续二十分钟并影响了订单。'],
  ['backup', 'n./v.', '备份', '科技', '核心', ['数据', '安全'], 'backup data', 'Please backup the database before you install the update.', '安装更新前请备份数据库。'],
  ['database', 'n.', '数据库', '科技', '核心', ['数据', '系统'], 'customer database', 'The customer database stores order history and contact details.', '客户数据库存储订单历史和联系方式。'],
  ['encryption', 'n.', '加密', '科技', '进阶', ['安全', '数据'], 'data encryption', 'Data encryption protects private information during transfer.', '数据加密在传输中保护私人信息。'],
  ['authentication', 'n.', '身份验证', '科技', '进阶', ['安全', '账号'], 'two-factor authentication', 'Two-factor authentication makes the account more secure.', '双因素身份验证让账号更安全。'],
  ['permission', 'n.', '权限，许可', '科技', '核心', ['安全', '系统'], 'user permission', 'The admin changed the user permission for the shared folder.', '管理员更改了共享文件夹的用户权限。'],
  ['integration', 'n.', '集成，整合', '科技', '高频', ['SaaS', '系统'], 'system integration', 'The new integration connects the CRM with the billing tool.', '新的集成把 CRM 和计费工具连接起来。'],
  ['automation', 'n.', '自动化', '科技', '高频', ['流程', '效率'], 'workflow automation', 'Workflow automation reduces repeated manual tasks.', '工作流自动化减少重复的手动任务。'],
  ['interface', 'n.', '界面，接口', '科技', '核心', ['产品', '系统'], 'user interface', 'The user interface should be simple and easy to scan.', '用户界面应该简洁且易于浏览。'],
  ['prototype', 'n.', '原型', '科技', '核心', ['产品', '设计'], 'build a prototype', 'The product team will build a prototype for user testing.', '产品团队会为用户测试制作原型。'],
  ['iteration', 'n.', '迭代', '科技', '进阶', ['产品', '开发'], 'product iteration', 'Each product iteration includes feedback from customers.', '每次产品迭代都包含客户反馈。'],
  ['latency', 'n.', '延迟', '科技', '进阶', ['网络', '性能'], 'reduce latency', 'The team improved the server to reduce latency.', '团队优化服务器以降低延迟。'],
  ['bandwidth', 'n.', '带宽', '科技', '进阶', ['网络', '性能'], 'network bandwidth', 'Video calls require enough network bandwidth.', '视频通话需要足够的网络带宽。'],
  ['storage', 'n.', '存储', '科技', '核心', ['云', '数据'], 'cloud storage', 'The plan includes one terabyte of cloud storage.', '该方案包含一 TB 云存储。'],
  ['migration', 'n.', '迁移', '科技', '进阶', ['系统', '数据'], 'data migration', 'The data migration will happen over the weekend.', '数据迁移会在周末进行。'],
  ['compatibility', 'n.', '兼容性', '科技', '进阶', ['产品', '测试'], 'browser compatibility', 'The QA team checks browser compatibility before release.', '测试团队在发布前检查浏览器兼容性。'],
  ['configuration', 'n.', '配置', '科技', '进阶', ['系统', '运维'], 'system configuration', 'Incorrect system configuration caused the login problem.', '错误的系统配置导致了登录问题。'],
  ['documentation', 'n.', '文档', '科技', '核心', ['开发', '支持'], 'technical documentation', 'Good technical documentation helps users solve problems faster.', '好的技术文档帮助用户更快解决问题。'],
  ['repository', 'n.', '代码仓库，资料库', '科技', '进阶', ['开发', '代码'], 'code repository', 'The developer pushed the fix to the code repository.', '开发者把修复推送到了代码仓库。'],
  ['version', 'n.', '版本', '科技', '核心', ['软件', '发布'], 'latest version', 'Please install the latest version of the mobile app.', '请安装手机应用的最新版本。'],
  ['feature', 'n.', '功能，特性', '科技', '核心', ['产品', '开发'], 'new feature', 'The new feature helps users review words offline.', '新功能帮助用户离线复习单词。'],
  ['bug', 'n.', '缺陷，错误', '科技', '核心', ['开发', '测试'], 'fix a bug', 'The developer fixed a bug in the search function.', '开发者修复了搜索功能中的一个错误。'],
  ['release', 'n./v.', '发布', '科技', '核心', ['软件', '产品'], 'release notes', 'The release notes explain the changes in this version.', '发布说明解释了这个版本的变化。'],
  ['monitor', 'v.', '监控', '科技', '高频', ['运维', '安全'], 'monitor traffic', 'The operations team monitors traffic during the campaign.', '运营团队在活动期间监控流量。'],
  ['incident', 'n.', '事件，事故', '科技', '进阶', ['运维', '安全'], 'security incident', 'The company reported a security incident last night.', '公司昨晚报告了一起安全事件。'],
  ['capacity', 'n.', '容量，能力', '科技', '高频', ['系统', '运营'], 'server capacity', 'Server capacity must increase before the holiday sale.', '节日促销前必须增加服务器容量。'],
  ['analytics', 'n.', '数据分析', '科技', '高频', ['数据', '营销'], 'web analytics', 'Web analytics helps the team understand user behavior.', '网页数据分析帮助团队理解用户行为。'],
  ['conversion', 'n.', '转化，转换', '科技', '进阶', ['营销', '数据'], 'conversion rate', 'The marketing team wants to improve the conversion rate.', '营销团队想提高转化率。'],
  ['campaign', 'n.', '营销活动，活动', '工作', '高频', ['市场', '销售'], 'marketing campaign', 'The campaign attracted many first-time customers.', '这次营销活动吸引了许多首次购买的客户。'],
  ['quotation', 'n.', '报价单', 'TOEIC', '高频', ['采购', '销售'], 'request a quotation', 'The buyer requested a quotation for five laptops.', '买方要求五台笔记本电脑的报价。'],
  ['reservation', 'n.', '预订，预约', 'TOEIC', '核心', ['差旅', '服务'], 'make a reservation', 'The assistant made a reservation for the business dinner.', '助理为商务晚餐做了预订。'],
  ['itinerary', 'n.', '行程', 'TOEIC', '高频', ['差旅', '安排'], 'travel itinerary', 'The travel itinerary includes two client visits.', '旅行行程包括两次客户拜访。'],
  ['accommodation', 'n.', '住宿', 'TOEIC', '进阶', ['差旅', '行政'], 'book accommodation', 'The company will book accommodation near the conference center.', '公司会预订会议中心附近的住宿。'],
  ['confirm', 'v.', '确认', 'TOEIC', '核心', ['沟通', '流程'], 'confirm a booking', 'Please confirm the booking by Friday afternoon.', '请在周五下午前确认预订。'],
  ['postpone', 'v.', '推迟', 'TOEIC', '核心', ['会议', '安排'], 'postpone a meeting', 'We had to postpone the meeting because the client was late.', '因为客户迟到，我们不得不推迟会议。'],
  ['reschedule', 'v.', '重新安排', 'TOEIC', '高频', ['会议', '安排'], 'reschedule an appointment', 'Can we reschedule the appointment for next Tuesday?', '我们能把预约改到下周二吗？'],
  ['attach', 'v.', '附上，附加', 'TOEIC', '核心', ['邮件', '文件'], 'attach a file', 'I attached the revised contract to the email.', '我在邮件中附上了修改后的合同。'],
  ['notify', 'v.', '通知', 'TOEIC', '核心', ['沟通', '流程'], 'notify customers', 'The company will notify customers before the price change.', '公司会在价格变更前通知客户。'],
  ['launch', 'v./n.', '发布，推出', '工作', '核心', ['产品', '市场'], 'launch a product', 'The team will launch the new product in September.', '团队将在九月推出新产品。'],
  ['retain', 'v.', '保留，留住', '工作', '进阶', ['客户', 'HR'], 'retain customers', 'Better service can help the company retain customers.', '更好的服务能帮助公司留住客户。'],
  ['resolve', 'v.', '解决', '工作', '核心', ['客服', '问题'], 'resolve an issue', 'The support team resolved the issue within one hour.', '支持团队在一小时内解决了问题。'],
  ['escalate', 'v.', '升级处理', '工作', '进阶', ['客服', '流程'], 'escalate a ticket', 'If the problem continues, escalate the ticket to engineering.', '如果问题持续，就把工单升级给工程团队。'],
  ['subscribe', 'v.', '订阅', '科技', '核心', ['SaaS', '产品'], 'subscribe to a plan', 'Users can subscribe to a yearly plan for a lower price.', '用户可以订阅年付方案以获得更低价格。'],
]

export const words = rawWords.map(([word, part, cn, group, level, tags, collocation, sentence, translation], index) => {
  const options = [
    word,
    ...distractors.filter((item) => item !== word && !sentence.toLowerCase().includes(item)).slice(index % 4, index % 4 + 3),
  ]

  while (options.length < 4) {
    const fallback = distractors[options.length + index]
    if (fallback && !options.includes(fallback)) options.push(fallback)
  }

  return {
    id: word,
    word,
    phonetic: '',
    part,
    cn,
    group,
    level,
    tags,
    collocation,
    sentence,
    translation,
    blank: sentence.replace(new RegExp(`\\b${word}\\b`, 'i'), '____'),
    options: options.slice(0, 4),
    note: `${group} 场景词：重点记住搭配 "${collocation}"，再放回例句理解。`,
  }
})

export const filters = ['全部', 'TOEIC', '工作', '科技']
